"""State Contract Closure scaffold generated by ``harness init``.

Replace these examples with project-specific writer -> consumer tests.  The
goal is to prove that every persisted governance state writer is consumed by
the check or gate that claims to enforce it.
"""


def test_state_contract_writer_consumer_closure() -> None:
    """Replace with real writer -> consumer closure tests for this project."""
    expected_examples = (
        "writer creates durable state",
        "consumer check reads that durable state",
        "missing state makes the consumer fail",
    )
    assert expected_examples


def test_state_contract_policy_documented() -> None:
    """Keep this project aligned with ``harness state-contract check``."""
    policy = "State Contract Closure requires writer -> consumer evidence"
    assert "State Contract Closure" in policy
    assert "writer -> consumer" in policy
    assert "harness state-contract check"
