"""Harness config loader.

The loader is deliberately minimal: it reads ``.harness/config.toml``
when present, falls back to :data:`defaults` otherwise, and exposes the
result as a :class:`harness_governance.models.HarnessConfig` instance.

We avoid pulling in a full TOML library: Python 3.11+ ships
:class:`tomllib` and the schema is small enough to make hand-rolled
parsing unnecessary on older runtimes. On 3.10 we require ``tomli``
only if the file uses advanced syntax (the current schema does not).
"""

from __future__ import annotations

import sys
from pathlib import Path

from ..logging_setup import get_logger
from ..models.schemas import HarnessConfig
from .defaults import DEFAULT_CONFIG_FILE

logger = get_logger("config")

if sys.version_info >= (3, 11):  # pragma: no cover - branch covered by version gate
    import tomllib as _toml
else:  # pragma: no cover
    try:
        import tomli as _toml  # type: ignore[no-redef]
    except ImportError as exc:  # pragma: no cover
        raise ImportError(
            "harness-governance requires Python 3.11+ or the 'tomli' package "
            "on 3.10 to read .harness/config.toml."
        ) from exc


def _coerce_path(value: object, *, base: Path) -> Path:
    if isinstance(value, Path):
        return value if value.is_absolute() else base / value
    if isinstance(value, str) and value:
        p = Path(value)
        return p if p.is_absolute() else base / p
    raise TypeError(f"Expected path string, got {type(value).__name__}: {value!r}")


def load_config(
    project_root: Path | None = None,
    *,
    config_file: Path | None = None,
) -> HarnessConfig:
    """Load ``.harness/config.toml`` (or fall back to defaults).

    Parameters
    ----------
    project_root:
        Root of the user's project. Defaults to the current working
        directory. All relative paths inside ``config.toml`` are
        resolved against this root.
    config_file:
        Override the config file location. Defaults to
        ``<project_root>/.harness/config.toml``.
    """
    root = (project_root or Path.cwd()).resolve()
    cfg_path = (config_file or (root / DEFAULT_CONFIG_FILE)).resolve()

    raw: dict[str, object] = {}
    if cfg_path.is_file():
        logger.debug("reading config: %s", cfg_path)
        with cfg_path.open("rb") as handle:
            raw = _toml.load(handle)
        logger.info("loaded %d field(s) from %s", len(raw), cfg_path)
    else:
        logger.debug("no config file at %s; using defaults", cfg_path)

    payload: dict[str, object] = dict(raw)
    payload.setdefault("project_root", root)
    payload["project_root"] = root

    for key in (
        "queue_file",
        "changes_root",
        "planning_root",
        "harness_dir",
    ):
        if key in raw:
            payload[key] = _coerce_path(raw[key], base=root)

    return HarnessConfig.model_validate(payload)


def write_default_config(
    project_root: Path,
    *,
    agent_platform: str,
    force: bool = False,
) -> Path:
    """Write ``.harness/config.toml`` with defaults.

    Returns the absolute path of the written file.
    """
    config_path = (project_root / DEFAULT_CONFIG_FILE).resolve()
    if config_path.exists() and not force:
        return config_path

    config_path.parent.mkdir(parents=True, exist_ok=True)
    body = (
        "# Harness governance configuration.\n"
        "# Generated by `harness init`. Edit values to override defaults.\n"
        f'agent_platform = "{agent_platform}"\n'
        'queue_file = "NEXT.md"\n'
        'changes_root = "docs/changes"\n'
        'planning_root = ".planning"\n'
        'harness_dir = ".harness"\n'
        'check_frequency = "targeted"\n'
    )
    config_path.write_text(body, encoding="utf-8")
    return config_path